// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("ManufacturerId", Name = "IX_EquipmentModel_1")]
[Index("EquipmentTypeId", Name = "IX_EquipmentModel_2")]
[Index("ModelName", Name = "IX_EquipmentModel_3")]
[Index("ManufacturerId", "EquipmentTypeId", Name = "IX_EquipmentModel_4")]
[Index("ManufacturerId", "EquipmentTypeId", "ModelName", Name = "IX_EquipmentModel_5")]
public partial class EquipmentModel
{
    [Key]
    public int EquipmentModelId { get; set; }

    public int ManufacturerId { get; set; }

    public int EquipmentTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string ModelName { get; set; }

    public bool Active { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartingDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndingDate { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [InverseProperty("EquipmentModel")]
    public virtual ICollection<EquipmentModelImage> EquipmentModelImage { get; set; } = new List<EquipmentModelImage>();

    [ForeignKey("EquipmentTypeId")]
    [InverseProperty("EquipmentModel")]
    public virtual EquipmentType EquipmentType { get; set; }

    [ForeignKey("ManufacturerId")]
    [InverseProperty("EquipmentModel")]
    public virtual EquipmentManufacturer Manufacturer { get; set; }
}