// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("EquipmentModelImageId", Name = "IX_EquipmentModelImage_1")]
public partial class EquipmentModelImage
{
    [Key]
    public int EquipmentModelImageId { get; set; }

    public int EquipmentId { get; set; }

    [Required]
    [StringLength(512)]
    public string EquipmentImageFile { get; set; }

    [Column(TypeName = "image")]
    public byte[] EquipmentImage { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }
}