// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("ManufacturerId", Name = "IX_GearType_1")]
[Index("ManufacturerId", "Active", Name = "IX_GearType_2")]
public partial class GearType
{
    [Key]
    public int GearTypeId { get; set; }

    public int ManufacturerId { get; set; }

    public bool Active { get; set; }

    [StringLength(100)]
    public string GearTypeName { get; set; }

    [StringLength(40)]
    public string GearSubType { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [InverseProperty("GearType")]
    public virtual ICollection<GearModel> GearModel { get; set; } = new List<GearModel>();

    [InverseProperty("GearType")]
    public virtual ICollection<GearTypeImage> GearTypeImage { get; set; } = new List<GearTypeImage>();
}