// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("ManufacturerId", Name = "idx_gearModel_1")]
[Index("GearTypeId", Name = "idx_gearModel_2")]
[Index("ModelName", Name = "idx_gearModel_3")]
[Index("ManufacturerId", "GearTypeId", Name = "idx_gearModel_4")]
[Index("ManufacturerId", "GearTypeId", "ModelName", Name = "idx_gearModel_5")]
public partial class GearModel
{
    [Key]
    public int GearModelId { get; set; }

    public int ManufacturerId { get; set; }

    public int GearTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string ModelName { get; set; }

    public bool Active { get; set; }

    public int? StartYear { get; set; }

    public int? EndYear { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [InverseProperty("GearModel")]
    public virtual ICollection<GearModelImage> GearModelImage { get; set; } = new List<GearModelImage>();

    [InverseProperty("GearModel")]
    public virtual ICollection<GearModelNotes> GearModelNotes { get; set; } = new List<GearModelNotes>();

    [ForeignKey("GearTypeId")]
    [InverseProperty("GearModel")]
    public virtual GearType GearType { get; set; }

    [ForeignKey("ManufacturerId")]
    [InverseProperty("GearModel")]
    public virtual Manufacturer Manufacturer { get; set; }
}