// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("GearTypeImageId", Name = "idx_gearTypeImage_1")]
public partial class GearTypeImage
{
    [Key]
    public int GearTypeImageId { get; set; }

    public int GearTypeId { get; set; }

    [Required]
    [StringLength(512)]
    public string ImageFile { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string ImageType { get; set; }

    public byte[] ImageData { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [ForeignKey("GearTypeId")]
    [InverseProperty("GearTypeImage")]
    public virtual GearType GearType { get; set; }
}