// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("ManufacturerId", Name = "IX_GearModel_1")]
[Index("GearTypeId", Name = "IX_GearModel_2")]
[Index("ModelName", Name = "IX_GearModel_3")]
[Index("ManufacturerId", "GearTypeId", Name = "IX_GearModel_4")]
[Index("ManufacturerId", "GearTypeId", "ModelName", Name = "IX_GearModel_5")]
public partial class GearModel
{
    [Key]
    public int GearModelId { get; set; }

    public int ManufacturerId { get; set; }

    public int GearTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string ModelName { get; set; }

    public bool Active { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartingDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndingDate { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [InverseProperty("GearModel")]
    public virtual ICollection<GearModelImage> GearModelImage { get; set; } = new List<GearModelImage>();

    [ForeignKey("GearTypeId")]
    [InverseProperty("GearModel")]
    public virtual GearType GearType { get; set; }

    [ForeignKey("ManufacturerId")]
    [InverseProperty("GearModel")]
    public virtual Manufacturer Manufacturer { get; set; }
}