// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("GearModelImageId", Name = "idx_gearModelImage_1")]
public partial class GearModelImage
{
    [Key]
    public int GearModelImageId { get; set; }

    public int GearModelId { get; set; }

    [Required]
    [StringLength(512)]
    public string ImageFile { get; set; }

    [Column(TypeName = "image")]
    public byte[] ImageData { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [ForeignKey("GearModelId")]
    [InverseProperty("GearModelImage")]
    public virtual GearModel GearModel { get; set; }
}