// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("CustomerId", Name = "idx_incidentReport_1")]
[Index("ClientId", Name = "idx_incidentReport_2")]
[Index("ReportedToId", Name = "idx_incidentReport_3")]
public partial class IncidentReport
{
    [Key]
    public int IncidentReportId { get; set; }

    public int? CustomerId { get; set; }

    public int? ClientId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReportDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? IncidentClosed { get; set; }

    public int? ReportedToId { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [InverseProperty("IncidentReport")]
    public virtual ICollection<IncidentReportHistory> IncidentReportHistory { get; set; } = new List<IncidentReportHistory>();
}