// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("IncidentReportId", Name = "idx_incidentReportHistory_1")]
public partial class IncidentReportHistory
{
    [Key]
    public int IncidentReportHistoryId { get; set; }

    public int IncidentReportId { get; set; }

    [StringLength(1024)]
    public string StatusText { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [ForeignKey("IncidentReportId")]
    [InverseProperty("IncidentReportHistory")]
    public virtual IncidentReport IncidentReport { get; set; }
}