// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("LocationType", Name = "idx_location_1")]
[Index("UserProfileId", Name = "idx_location_2")]
[Index("ClientId", Name = "idx_location_3")]
public partial class Location
{
    [Key]
    public int LocationId { get; set; }

    public int? UserProfileId { get; set; }

    public int? ClientId { get; set; }

    public int? ManufacturerId { get; set; }

    [StringLength(10)]
    public string LocationType { get; set; }

    [StringLength(100)]
    public string Address1 { get; set; }

    [StringLength(100)]
    public string Address2 { get; set; }

    [StringLength(100)]
    public string Address3 { get; set; }

    [StringLength(100)]
    public string City { get; set; }

    [StringLength(50)]
    public string State { get; set; }

    [StringLength(20)]
    public string PostalCode { get; set; }

    [StringLength(100)]
    public string Country { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }
}