// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("ManufacturerId", Name = "idx_manufacturer")]
public partial class ManufacturerNotes
{
    [Key]
    public int NoteId { get; set; }

    public int ManufacturerId { get; set; }

    [StringLength(1024)]
    public string NoteText { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [ForeignKey("ManufacturerId")]
    [InverseProperty("ManufacturerNotes")]
    public virtual Manufacturer Manufacturer { get; set; }
}