// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

public partial class MusiciansGearRegistryContext : DbContext
{
    public MusiciansGearRegistryContext(DbContextOptions<MusiciansGearRegistryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<ClientContact> ClientContact { get; set; }

    public virtual DbSet<EquipmentManufacturer> EquipmentManufacturer { get; set; }

    public virtual DbSet<EquipmentModel> EquipmentModel { get; set; }

    public virtual DbSet<EquipmentModelImage> EquipmentModelImage { get; set; }

    public virtual DbSet<EquipmentType> EquipmentType { get; set; }

    public virtual DbSet<EquipmentTypeImage> EquipmentTypeImage { get; set; }

    public virtual DbSet<IncidentReport> IncidentReport { get; set; }

    public virtual DbSet<IncidentReportHistory> IncidentReportHistory { get; set; }

    public virtual DbSet<Location> Location { get; set; }

    public virtual DbSet<TransferHistory> TransferHistory { get; set; }

    public virtual DbSet<UserEquipment> UserEquipment { get; set; }

    public virtual DbSet<UserEquipmentImage> UserEquipmentImage { get; set; }

    public virtual DbSet<UserProfile> UserProfile { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Client__E67E1A24A3EC4D4A");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ClientContact>(entity =>
        {
            entity.HasKey(e => e.ClientContactId).HasName("PK__ClientCo__421FAD880F36F0E5");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<EquipmentManufacturer>(entity =>
        {
            entity.HasKey(e => e.ManufacturerId).HasName("PK__Equipmen__357E5CC1946B3963");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<EquipmentModel>(entity =>
        {
            entity.HasKey(e => e.EquipmentModelId).HasName("PK__Equipmen__13C415FAAE6B4094");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<EquipmentModelImage>(entity =>
        {
            entity.HasKey(e => e.EquipmentModelImageId).HasName("PK__Equipmen__C7A5B93C85F76B90");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<EquipmentType>(entity =>
        {
            entity.HasKey(e => e.EquipmentTypeId).HasName("PK__Equipmen__554726FCD6216B64");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<EquipmentTypeImage>(entity =>
        {
            entity.HasKey(e => e.EquipmentTypeImageId).HasName("PK__Equipmen__A477772E61DF0BD0");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.IncidentReportId).HasName("PK__Incident__807950308014AE7B");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<IncidentReportHistory>(entity =>
        {
            entity.HasKey(e => e.IncidentReportHistoryId).HasName("PK__Incident__51F62EB5D059A1CE");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA49736D53E86");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TransferHistory>(entity =>
        {
            entity.HasKey(e => e.TransferHistoryId).HasName("PK__Transfer__593FCDD3E33F56AE");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserEquipment>(entity =>
        {
            entity.HasKey(e => e.UserEquipmentId).HasName("PK__UserEqui__20DDC95C2CE62BAE");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsOriginal).HasDefaultValue(true);
        });

        modelBuilder.Entity<UserEquipmentImage>(entity =>
        {
            entity.HasKey(e => e.UserEquipmentImageId).HasName("PK__UserEqui__EF24362A6F564194");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserProfileId).HasName("PK__UserProf__9E267F6267F2F25F");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UserProfileStatus).HasDefaultValue(0);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}