// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

public partial class MusiciansGearRegistryContext : DbContext
{
    public MusiciansGearRegistryContext(DbContextOptions<MusiciansGearRegistryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<ClientContact> ClientContact { get; set; }

    public virtual DbSet<GearModel> GearModel { get; set; }

    public virtual DbSet<GearModelImage> GearModelImage { get; set; }

    public virtual DbSet<GearType> GearType { get; set; }

    public virtual DbSet<GearTypeImage> GearTypeImage { get; set; }

    public virtual DbSet<IncidentReport> IncidentReport { get; set; }

    public virtual DbSet<IncidentReportHistory> IncidentReportHistory { get; set; }

    public virtual DbSet<Location> Location { get; set; }

    public virtual DbSet<Manufacturer> Manufacturer { get; set; }

    public virtual DbSet<TransferHistory> TransferHistory { get; set; }

    public virtual DbSet<UserGear> UserGear { get; set; }

    public virtual DbSet<UserGearImage> UserGearImage { get; set; }

    public virtual DbSet<UserProfile> UserProfile { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Client__E67E1A241C3B8E42");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ClientContact>(entity =>
        {
            entity.HasKey(e => e.ClientContactId).HasName("PK__ClientCo__421FAD88146B145A");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<GearModel>(entity =>
        {
            entity.HasKey(e => e.GearModelId).HasName("PK__GearMode__9ECFAE91E456D031");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearModel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GearType");

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.GearModel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GearManufacturer");
        });

        modelBuilder.Entity<GearModelImage>(entity =>
        {
            entity.HasKey(e => e.GearModelImageId).HasName("PK__GearMode__BD99D5E5FE501989");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearModel).WithMany(p => p.GearModelImage)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GearModelImage");
        });

        modelBuilder.Entity<GearType>(entity =>
        {
            entity.HasKey(e => e.GearTypeId).HasName("PK__GearType__26A4FE7E1E5758FE");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<GearTypeImage>(entity =>
        {
            entity.HasKey(e => e.GearTypeImageId).HasName("PK__GearType__F527FEAECBE0737F");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearTypeImage)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GearTypeImage");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.IncidentReportId).HasName("PK__Incident__807950303B1BFE3C");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<IncidentReportHistory>(entity =>
        {
            entity.HasKey(e => e.IncidentReportHistoryId).HasName("PK__Incident__51F62EB5DC95C06A");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA497F3DB1611");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Manufacturer>(entity =>
        {
            entity.HasKey(e => e.ManufacturerId).HasName("PK__Manufact__357E5CC1E39E1E6A");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TransferHistory>(entity =>
        {
            entity.HasKey(e => e.TransferHistoryId).HasName("PK__Transfer__593FCDD3939A381D");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserGear>(entity =>
        {
            entity.HasKey(e => e.UserGearId).HasName("PK__UserGear__6525EE7A5C3423B6");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsOriginal).HasDefaultValue(true);
        });

        modelBuilder.Entity<UserGearImage>(entity =>
        {
            entity.HasKey(e => e.UserGearImageId).HasName("PK__UserGear__68678F08F118999F");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.UserGear).WithMany(p => p.UserGearImage)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserGearImage");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserProfileId).HasName("PK__UserProf__9E267F62F51CF66B");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UserProfileStatus).HasDefaultValue(0);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}