// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

public partial class MusiciansGearRegistryContext : DbContext
{
    public MusiciansGearRegistryContext(DbContextOptions<MusiciansGearRegistryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<ClientContact> ClientContact { get; set; }

    public virtual DbSet<GearModel> GearModel { get; set; }

    public virtual DbSet<GearModelImage> GearModelImage { get; set; }

    public virtual DbSet<GearModelNotes> GearModelNotes { get; set; }

    public virtual DbSet<GearType> GearType { get; set; }

    public virtual DbSet<GearTypeImage> GearTypeImage { get; set; }

    public virtual DbSet<GearTypeNotes> GearTypeNotes { get; set; }

    public virtual DbSet<IncidentReport> IncidentReport { get; set; }

    public virtual DbSet<IncidentReportHistory> IncidentReportHistory { get; set; }

    public virtual DbSet<Location> Location { get; set; }

    public virtual DbSet<Manufacturer> Manufacturer { get; set; }

    public virtual DbSet<ManufacturerNotes> ManufacturerNotes { get; set; }

    public virtual DbSet<TransferHistory> TransferHistory { get; set; }

    public virtual DbSet<UserGear> UserGear { get; set; }

    public virtual DbSet<UserGearImage> UserGearImage { get; set; }

    public virtual DbSet<UserProfile> UserProfile { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Client__E67E1A24C9963309");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ClientContact>(entity =>
        {
            entity.HasKey(e => e.ClientContactId).HasName("PK__ClientCo__421FAD88F2C452B6");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<GearModel>(entity =>
        {
            entity.HasKey(e => e.GearModelId).HasName("PK__GearMode__9ECFAE91BEFFA145");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearModel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearModel_gearType");

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.GearModel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearManufacturer");
        });

        modelBuilder.Entity<GearModelImage>(entity =>
        {
            entity.HasKey(e => e.GearModelImageId).HasName("PK__GearMode__BD99D5E55A17A9C1");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearModel).WithMany(p => p.GearModelImage)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearModelImage");
        });

        modelBuilder.Entity<GearModelNotes>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("PK__GearMode__EACE355F70BEDCBF");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearModel).WithMany(p => p.GearModelNotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearModel");
        });

        modelBuilder.Entity<GearType>(entity =>
        {
            entity.HasKey(e => e.GearTypeId).HasName("PK__GearType__26A4FE7EE3606F3E");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<GearTypeImage>(entity =>
        {
            entity.HasKey(e => e.GearTypeImageId).HasName("PK__GearType__F527FEAEE902C065");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearTypeImage)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearTypeImage");
        });

        modelBuilder.Entity<GearTypeNotes>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("PK__GearType__EACE355F1EAECE6B");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearTypeNotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearType");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.IncidentReportId).HasName("PK__Incident__80795030AFF80799");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<IncidentReportHistory>(entity =>
        {
            entity.HasKey(e => e.IncidentReportHistoryId).HasName("PK__Incident__51F62EB5CC9A1FE7");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IncidentReport).WithMany(p => p.IncidentReportHistory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_incidentReport");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA49768F35876");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Manufacturer>(entity =>
        {
            entity.HasKey(e => e.ManufacturerId).HasName("PK__Manufact__357E5CC12589CD17");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ManufacturerNotes>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("PK__Manufact__EACE355F68F29394");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.ManufacturerNotes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_manufacturer");
        });

        modelBuilder.Entity<TransferHistory>(entity =>
        {
            entity.HasKey(e => e.TransferHistoryId).HasName("PK__Transfer__593FCDD3E9D4029C");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserGear>(entity =>
        {
            entity.HasKey(e => e.UserGearId).HasName("PK__UserGear__6525EE7A77D17A25");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsOriginal).HasDefaultValue(true);
        });

        modelBuilder.Entity<UserGearImage>(entity =>
        {
            entity.HasKey(e => e.UserGearImageId).HasName("PK__UserGear__68678F0869ED7CEE");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.UserGear).WithMany(p => p.UserGearImage)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_userGearImage");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserProfileId).HasName("PK__UserProf__9E267F62BAE0CC93");

            entity.Property(e => e.CreatedBy).HasDefaultValue("system");
            entity.Property(e => e.CreatedOn).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UserProfileStatus).HasDefaultValue(0);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}