// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusiciansGearRegistry.Data.Models
{
    public partial class sp_GearTypesByManufacturerResult
    {
        public int GearTypeId { get; set; }
        public bool Active { get; set; }
        [StringLength(100)]
        public string GearTypeName { get; set; }
    }
}
