// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

public partial class UserProfile
{
    [Key]
    public int UserProfileId { get; set; }

    public Guid UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(2)]
    public string MiddleInitial { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateRegistered { get; set; }

    [Required]
    [StringLength(40)]
    public string UserName { get; set; }

    [Required]
    [StringLength(255)]
    public string EMailAddress { get; set; }

    [StringLength(50)]
    public string PhoneNumber { get; set; }

    public int? UserProfileStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    [Required]
    [StringLength(256)]
    public string UserPassword { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }
}