// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("UserProfileId", "GearModelId", Name = "idx_userGear_1")]
public partial class UserGear
{
    [Key]
    public int UserGearId { get; set; }

    public int UserProfileId { get; set; }

    public bool Active { get; set; }

    public int GearModelId { get; set; }

    [StringLength(100)]
    public string SerialNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateAcquired { get; set; }

    public bool? IsOriginal { get; set; }

    public int? ClientId_PurchasedFrom { get; set; }

    public string GearNotes { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [InverseProperty("UserGear")]
    public virtual ICollection<UserGearImage> UserGearImage { get; set; } = new List<UserGearImage>();
}