// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Data.Models;

[Index("UserProfileId", "RoleId", Name = "idx_userrole")]
public partial class UserRoles
{
    [Key]
    public int UserRoleId { get; set; }

    public int UserProfileId { get; set; }

    public int RoleId { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedOn { get; set; }

    [StringLength(50)]
    public string DeletedBy { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("UserRoles")]
    public virtual ApplicationRoles Role { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("UserRoles")]
    public virtual UserProfile UserProfile { get; set; }
}