// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class Client
{
    public int ClientId { get; set; }

    public string ClientName { get; set; }

    public int? ClientTypeId { get; set; }

    public string ClientStatus { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }
}