// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class GearType
{
    public int GearTypeId { get; set; }

    public bool Active { get; set; }

    public string GearTypeName { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<GearModel> GearModels { get; set; } = new List<GearModel>();

    public virtual ICollection<GearTypeImage> GearTypeImages { get; set; } = new List<GearTypeImage>();

    public virtual ICollection<GearTypeNote> GearTypeNotes { get; set; } = new List<GearTypeNote>();
}