// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class GearModel
{
    public int GearModelId { get; set; }

    public int ManufacturerId { get; set; }

    public int GearTypeId { get; set; }

    public string ModelName { get; set; }

    public bool Active { get; set; }

    public DateTime? StartingDate { get; set; }

    public DateTime? EndingDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<GearModelImage> GearModelImages { get; set; } = new List<GearModelImage>();

    public virtual ICollection<GearModelNote> GearModelNotes { get; set; } = new List<GearModelNote>();

    public virtual GearType GearType { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }
}