// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class GearTypeImage
{
    public int GearTypeImageId { get; set; }

    public int GearTypeId { get; set; }

    public string ImageFile { get; set; }

    public string ImageType { get; set; }

    public byte[] ImageData { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }

    public virtual GearType GearType { get; set; }
}