// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MusiciansGearRegistry.Api.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MusiciansGearRegistry.Api.Models
{
    public partial interface IMusiciansGearRegistryDbContextProcedures
    {
        Task<List<sp_GearModelsByManufacturerAndTypeResult>> sp_GearModelsByManufacturerAndTypeAsync(int? manufacturerId, int? gearTypeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GearTypesByManufacturerResult>> sp_GearTypesByManufacturerAsync(int? manufacturerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
