// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class IncidentReport
{
    public int IncidentReportId { get; set; }

    public int? CustomerId { get; set; }

    public int? ClientId { get; set; }

    public DateTime? ReportDate { get; set; }

    public DateTime? IncidentClosed { get; set; }

    public int? ReportedToId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<IncidentReportHistory> IncidentReportHistories { get; set; } = new List<IncidentReportHistory>();
}