// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class Location
{
    public int LocationId { get; set; }

    public int? UserProfileId { get; set; }

    public int? ClientId { get; set; }

    public int? ManufacturerId { get; set; }

    public string LocationType { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }
}