// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class Manufacturer
{
    public int ManufacturerId { get; set; }

    public string ManufacturerName { get; set; }

    public bool? Active { get; set; }

    public int? PrimaryLocationId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<GearModel> GearModels { get; set; } = new List<GearModel>();

    public virtual ICollection<ManufacturerNote> ManufacturerNotes { get; set; } = new List<ManufacturerNote>();
}