// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MusiciansGearRegistry.Api.Models;

public partial class MusiciansGearRegistryDbContext : DbContext
{
    public MusiciansGearRegistryDbContext(DbContextOptions<MusiciansGearRegistryDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<ClientContact> ClientContacts { get; set; }

    public virtual DbSet<GearModel> GearModels { get; set; }

    public virtual DbSet<GearModelImage> GearModelImages { get; set; }

    public virtual DbSet<GearModelNote> GearModelNotes { get; set; }

    public virtual DbSet<GearType> GearTypes { get; set; }

    public virtual DbSet<GearTypeImage> GearTypeImages { get; set; }

    public virtual DbSet<GearTypeNote> GearTypeNotes { get; set; }

    public virtual DbSet<IncidentReport> IncidentReports { get; set; }

    public virtual DbSet<IncidentReportHistory> IncidentReportHistories { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Manufacturer> Manufacturers { get; set; }

    public virtual DbSet<ManufacturerNote> ManufacturerNotes { get; set; }

    public virtual DbSet<TransferHistory> TransferHistories { get; set; }

    public virtual DbSet<UserGear> UserGears { get; set; }

    public virtual DbSet<UserGearImage> UserGearImages { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("PK__Client__E67E1A246D46AA86");

            entity.ToTable("Client");

            entity.Property(e => e.ClientName).HasMaxLength(100);
            entity.Property(e => e.ClientStatus).HasMaxLength(20);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<ClientContact>(entity =>
        {
            entity.HasKey(e => e.ClientContactId).HasName("PK__ClientCo__421FAD88F81962C1");

            entity.ToTable("ClientContact");

            entity.HasIndex(e => e.ClientId, "idx_ClientContact1");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("EMailAddress");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);
        });

        modelBuilder.Entity<GearModel>(entity =>
        {
            entity.HasKey(e => e.GearModelId).HasName("PK__GearMode__9ECFAE91587BB082");

            entity.ToTable("GearModel");

            entity.HasIndex(e => e.ManufacturerId, "idx_gearModel_1");

            entity.HasIndex(e => e.GearTypeId, "idx_gearModel_2");

            entity.HasIndex(e => e.ModelName, "idx_gearModel_3");

            entity.HasIndex(e => new { e.ManufacturerId, e.GearTypeId }, "idx_gearModel_4");

            entity.HasIndex(e => new { e.ManufacturerId, e.GearTypeId, e.ModelName }, "idx_gearModel_5");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.EndingDate).HasColumnType("datetime");
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.StartingDate).HasColumnType("datetime");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearModels)
                .HasForeignKey(d => d.GearTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearModel_gearType");

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.GearModels)
                .HasForeignKey(d => d.ManufacturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearManufacturer");
        });

        modelBuilder.Entity<GearModelImage>(entity =>
        {
            entity.HasKey(e => e.GearModelImageId).HasName("PK__GearMode__BD99D5E5316DED3F");

            entity.ToTable("GearModelImage");

            entity.HasIndex(e => e.GearModelImageId, "idx_gearModelImage_1");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ImageFile)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.ImageType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.GearModel).WithMany(p => p.GearModelImages)
                .HasForeignKey(d => d.GearModelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearModelImage");
        });

        modelBuilder.Entity<GearModelNote>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("PK__GearMode__EACE355FDA9AA2B9");

            entity.HasIndex(e => e.GearModelId, "idx_gearModel");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.NoteText).HasMaxLength(1024);

            entity.HasOne(d => d.GearModel).WithMany(p => p.GearModelNotes)
                .HasForeignKey(d => d.GearModelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearModel");
        });

        modelBuilder.Entity<GearType>(entity =>
        {
            entity.HasKey(e => e.GearTypeId).HasName("PK__GearType__26A4FE7EB91CB718");

            entity.ToTable("GearType");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.GearTypeName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<GearTypeImage>(entity =>
        {
            entity.HasKey(e => e.GearTypeImageId).HasName("PK__GearType__F527FEAE775C1A5E");

            entity.ToTable("GearTypeImage");

            entity.HasIndex(e => e.GearTypeImageId, "idx_gearTypeImage_1");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ImageFile)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.ImageType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.GearType).WithMany(p => p.GearTypeImages)
                .HasForeignKey(d => d.GearTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearTypeImage");
        });

        modelBuilder.Entity<GearTypeNote>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("PK__GearType__EACE355F53E736DB");

            entity.HasIndex(e => e.GearTypeId, "idx_gearType");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.NoteText).HasMaxLength(1024);

            entity.HasOne(d => d.GearType).WithMany(p => p.GearTypeNotes)
                .HasForeignKey(d => d.GearTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_gearType");
        });

        modelBuilder.Entity<IncidentReport>(entity =>
        {
            entity.HasKey(e => e.IncidentReportId).HasName("PK__Incident__807950309868D434");

            entity.ToTable("IncidentReport");

            entity.HasIndex(e => e.CustomerId, "idx_incidentReport_1");

            entity.HasIndex(e => e.ClientId, "idx_incidentReport_2");

            entity.HasIndex(e => e.ReportedToId, "idx_incidentReport_3");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.IncidentClosed).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.ReportDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<IncidentReportHistory>(entity =>
        {
            entity.HasKey(e => e.IncidentReportHistoryId).HasName("PK__Incident__51F62EB509ECDB48");

            entity.ToTable("IncidentReportHistory");

            entity.HasIndex(e => e.IncidentReportId, "idx_incidentReportHistory_1");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.StatusText).HasMaxLength(1024);

            entity.HasOne(d => d.IncidentReport).WithMany(p => p.IncidentReportHistories)
                .HasForeignKey(d => d.IncidentReportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_incidentReport");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA497084C9490");

            entity.ToTable("Location");

            entity.HasIndex(e => e.LocationType, "idx_location_1");

            entity.HasIndex(e => e.UserProfileId, "idx_location_2");

            entity.HasIndex(e => e.ClientId, "idx_location_3");

            entity.Property(e => e.Address1).HasMaxLength(100);
            entity.Property(e => e.Address2).HasMaxLength(100);
            entity.Property(e => e.Address3).HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.LocationType).HasMaxLength(10);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PostalCode).HasMaxLength(20);
            entity.Property(e => e.State).HasMaxLength(50);
        });

        modelBuilder.Entity<Manufacturer>(entity =>
        {
            entity.HasKey(e => e.ManufacturerId).HasName("PK__Manufact__357E5CC134595A5B");

            entity.ToTable("Manufacturer");

            entity.HasIndex(e => e.ManufacturerName, "idx_manufacturerName");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ManufacturerName).HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
        });

        modelBuilder.Entity<ManufacturerNote>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("PK__Manufact__EACE355F1A252D4B");

            entity.HasIndex(e => e.ManufacturerId, "idx_manufacturer");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.NoteText).HasMaxLength(1024);

            entity.HasOne(d => d.Manufacturer).WithMany(p => p.ManufacturerNotes)
                .HasForeignKey(d => d.ManufacturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_manufacturer");
        });

        modelBuilder.Entity<TransferHistory>(entity =>
        {
            entity.HasKey(e => e.TransferHistoryId).HasName("PK__Transfer__593FCDD39DB81400");

            entity.ToTable("TransferHistory");

            entity.HasIndex(e => e.UserProfileId, "idx_TransferHistory_1");

            entity.HasIndex(e => e.ClientId, "idx_TransferHistory_2");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PurchasePrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TransferDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<UserGear>(entity =>
        {
            entity.HasKey(e => e.UserGearId).HasName("PK__UserGear__6525EE7AF2057BC2");

            entity.ToTable("UserGear");

            entity.HasIndex(e => new { e.UserProfileId, e.GearModelId }, "idx_userGear_1");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.ClientIdPurchasedFrom).HasColumnName("ClientId_PurchasedFrom");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DateAcquired).HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.IsOriginal).HasDefaultValue(true);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.SerialNumber).HasMaxLength(100);
        });

        modelBuilder.Entity<UserGearImage>(entity =>
        {
            entity.HasKey(e => e.UserGearImageId).HasName("PK__UserGear__68678F08174D9B08");

            entity.ToTable("UserGearImage");

            entity.HasIndex(e => e.UserGearId, "idx_userGearImage_1");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.ImageFile)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.ImageType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");

            entity.HasOne(d => d.UserGear).WithMany(p => p.UserGearImages)
                .HasForeignKey(d => d.UserGearId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_userGearImage");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.HasKey(e => e.UserProfileId).HasName("PK__UserProf__9E267F62625963CC");

            entity.ToTable("UserProfile");

            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("system");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DateRegistered).HasColumnType("datetime");
            entity.Property(e => e.DeletedBy).HasMaxLength(50);
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.EmailAddress)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("EMailAddress");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastLogin).HasColumnType("datetime");
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.MiddleInitial).HasMaxLength(2);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.PhoneNumber).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.UserProfileStatus).HasDefaultValue(0);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}