// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MusiciansGearRegistry.Api.Models;

public partial class UserGear
{
    public int UserGearId { get; set; }

    public int UserProfileId { get; set; }

    public bool Active { get; set; }

    public int GearModelId { get; set; }

    public string SerialNumber { get; set; }

    public DateTime? DateAcquired { get; set; }

    public bool? IsOriginal { get; set; }

    public int? ClientIdPurchasedFrom { get; set; }

    public string GearNotes { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<UserGearImage> UserGearImages { get; set; } = new List<UserGearImage>();
}